/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package hello_10

import com.mine.hello.DB

class App {

    static void main(String[] args) {
        def db = new DB()
        
        def results = db.getQryDtl('2019-11-27', 1)
        results.each() { x ->
            println "${x['acc']}, ${x['amt']}, ${x['rpt_sum']}, ${x['tran_date']}"
        }

        def results_02 = db.getQryDtl_02('2019-11-28', 1)
        results_02.each() { x ->
            println "${x.acc}, ${x.amt}, ${x.rptSum}, ${x.tranDate}"
        }
    }
}
